---
title: "Search"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{css echo=FALSE}
d-title {
    display: none;
  }
.dataTables_wrapper .dataTables_filter{
    float: left;
}
.dataTables_wrapper .dataTables_length{
    float: right;
}
```

```{r searcher, echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(DT)
library(tidyverse)

id <- "118r1bHNAH2-YECIsqXeRiW6tH369l0pN"
sessions<-read.csv(paste0("https://docs.google.com/u/0/uc?id=",id,"&export=download"),sep=";")
colnames(sessions)[[1]]="DATE"
id <- "12Uc6uypR3AqKcWb_PS1pnDCmukrplbSI"
papers<-read.csv(paste0("https://docs.google.com/u/0/uc?id=",id,"&export=download"),sep=";")
colnames(papers)[[1]]="IDSESS"
id<-"12SQi3N-ArwXD-wKGMT7jAWEBaIvn8l-a"
links<-read.csv(paste0("https://docs.google.com/u/0/uc?id=",id,"&export=download"),sep=";")
papers<-papers %>% left_join(links,by = c("FOLDER"="IDpap_fol")) %>%
  mutate(Contribute=paste0("<b>",Title,"</b></br><i>",Authors,"</i>"), Link=Links)%>% 
  select(IDSESS,Contribute,Link)


```


```{r searcher2, echo=FALSE, message=FALSE, warning=FALSE}
joint<-sessions %>% left_join(papers,by=c("IDSESS"="IDSESS"))
DF<-joint %>% select(DATE,ORARIOLUNGO,IDSESS,Contribute,Room,CHAIR,DISCUSSANT,Link) %>% 
  mutate("When and where"=case_when(
    grepl("CON",IDSESS) ~ paste0(DATE,"&nbsp;&#x2011;&nbsp;", ORARIOLUNGO," </br> ", IDSESS, " Room: "),
    grepl("SPE",IDSESS) ~ paste0(DATE,"&nbsp;&#x2011;&nbsp;", ORARIOLUNGO," </br> ", IDSESS, " Room: ", Room, " </br> Chair:&nbsp;", CHAIR, "</br>Disc.: ", DISCUSSANT),
    grepl("SOL",IDSESS) ~ paste0(DATE,"&nbsp;&#x2011;&nbsp;", ORARIOLUNGO," </br> ", IDSESS, " Room: ", Room, "</br> Chair:&nbsp;", CHAIR),
    grepl("COFFEE",IDSESS) ~ paste0(DATE,"&nbsp;&#x2011;&nbsp;", ORARIOLUNGO," </br> ", IDSESS, " Room: "),
    TRUE ~ paste0(DATE,"&nbsp;&#x2011;&nbsp;", ORARIOLUNGO," </br> ", IDSESS, " Room: ")
      ),
    Contribution=Contribute,
    "Click to download"=if_else(!is.na(Link),paste0("<a href=\"",Link,"\">View</a>"),"not avail.")) %>% 
  select("When and where",Contribution,"Click to download")

# cb<-JS(
# "$(document).ready(function (){",
#     "var table = $('#example').DataTable({",
#      "  'initComplete': function(){",
#     "      $('#example_filter').detach().appendTo('#newSearch');",
#      "  },",
#    "    'language': { 'search':'' } ",
#   "  });",
# "});"
# )

DT::datatable(DF,rownames = FALSE,escape=FALSE,
             # callback = cb,
              options = list(
                       pageLength = 20
                         )
              )
```
# {-}

<a href="#top">Back to top</a>
